name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  RUST_BACKTRACE: 1
  CI: 1

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt,clippy
          profile: minimal

      - name: cargo fmt -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  test:
    name: Test ${{ matrix.name }}
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    needs: [style]
    continue-on-error: true

    strategy:
      matrix:
        name:
          - linux / stable
          - linux / beta
          - linux / nightly
          - macos / stable
          - windows / stable-x86_64-msvc
          - windows / stable-i686-msvc
          - windows / stable-x86_64-gnu
          - windows / stable-i686-gnu
        include:
          - name: linux / stable
          - name: linux / beta
            rs_toolchain: beta
          - name: linux / nightly
            rs_toolchain: nightly

          - name: macos / stable
            os: macos-latest

          - name: windows / stable-x86_64-msvc
            os: windows-latest
            rs_target: x86_64-pc-windows-msvc
          - name: windows / stable-i686-msvc
            os: windows-latest
            rs_target: i686-pc-windows-msvc
          - name: windows / stable-x86_64-gnu
            os: windows-latest
            rs_target: x86_64-pc-windows-gnu
          - name: windows / stable-i686-gnu
            os: windows-latest
            rs_target: i686-pc-windows-gnu

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rs_toolchain || 'stable' }}
          target: ${{ matrix.rs_target }}
          profile: minimal

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: cargo test -- --test-threads 1
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --test-threads 1

  docs:
    name: Docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Check Documentation
        env:
          RUSTDOCFLAGS: -D warnings
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps --all-features
